### ISSUE TITLE
SQL Server AdventureWorks tables

### ISSUE THREAD

**Issue by pdadey** [arrahtech/osdq-core#38]
Loaded SQL Server AdventureWorks DB tables.
Tables do not represent the SQL Server schema ie Person.PersonPhone
When I click on a table name an "Invalid object name 'PersonPhone'" Error Mesage is presented
and 
java.lang.Exception:
 Warning: Could not Get Pattern Information 
...
 Error: Could not Get Distribution Information
is listed in the cmd window

**Comment by arrah** [comment]
I hope you have filled schema Name and category Name for SQL Server. Hopefully this link with help you.

https://sourceforge.net/p/dataquality/discussion/602692/thread/2677c28c/

osDQ uses "cat"."table"  if category name is not empty.  Let us know if it solves the problem.

**Comment by pdadey** [comment]
Hi

I have configured  the DB and Schema filters for SQL Server and Oracle DB connections, however the table metadata is loaded but not the related table data.

In addition I have found the following:

  1.  Connection not saved when Added
  2.  SQL Keywords have leading space in dataset
  3.  Spelling:
                                Auto Increamental->Auto Incremental
                                Exeception->Exception

  1.  Functions Information menu:
                                Other DB Function types not listed ie
                                Aggregate Fx:COUNT(), MIN(), MAX() etc
                                Windows Fx:LEAD(), LAG(), FIRST_VALUE(), LAST_VALUE() etc

**Comment by arrah** [comment]
Thanks for spending time with osDQ.
Please go to Tools --> SQL interface. Type a simple sql query SELECT....... from "qualifier"."table". Once you are able to successfully run the query the "qualifier" should be your catalog name. Let me know if it works. I hope you are using JDBC driver for Oracle.

1.) Add connection works only in business Rule --> add datasource. It is a known issues  - a bug will be filed.

2.) We use database connection to fetch keywords. if databases added space leading or trailing keyword then it will appear. osDQ does not add sapce

3.) it has been corrected.

1.) We will enhance the function to get System and User function which is now available. I will add an enhance request.

**Comment by pdadey** [comment]
Below an example of the spaces prefixing SQL Keywords for an Oracle connection:
[cid:image003.png@01D39C3B.0AD82FA0]

Also could you please add columns:

  1.  MinVal
  2.  MaxVal
  3.  Mean
  4.  LeftPad
  5.  RightPad


To the Table and Database Summary Info data grids?

**Comment by arrah** [comment]
Hi,
For some reason I am not able to see attached files. Please send it to vivek_ks at hotmaildotcom.

Are you able to connect tables and analyze them ?

I will add   those columns. It will be good info to capture. 

1.  MinVal
  2.  MaxVal
  3.  Mean
  4.  LeftPad
  5.  RightPad
 
However, now you get 1.  MinVal 2.  MaxVal 3.  Mean value in analysis panel.

**Comment by pdadey** [comment]
Hi
I have forwarded an email with screenshot to your vivek account.

Yes I can connect to a single named schema and analyse the tables.
I can also connect (for SQL Server using the “.” Default).
But it allows me to view only the metadata for tables contained in the database.  Can wildcards or a comma separated list be configured to be used in the Filters?

I noticed that the configuration folder contains the files below

  1.  configFile.txt
  2.  DBConnections.xml

Can either of these be configured so that they can be picked from the Connections drop down when you start osDQ?

Can you also please add MinLength and MaxLength to the list of columns below too?

Lastly – I just like you to know that osDQ is a fantastic product!

**Comment by arrah** [comment]
At present wildcard and comma separated is not allowed but it is a good idea. We will see how multiple databases can be supported.

DBConnections.xml is file place where connection is stored in business rules menu. You can use configFile.txt and unhash the DB parameter you are looking for.

if you run osDQ like
command> runProfiler.[sh\bat] configFile.txt is will load the database programmatically.

Thanks for you kind words.

**Comment by arrah** [comment]
resolved. Next release will have added functionality
