### ISSUE TITLE
To add support for UDFs

### ISSUE THREAD

**Issue by arun-y** [arrahtech/osdq-core#39]
Currently only pre-defined functions are available for users while defining data quality rules. This could be limiting is certain situations for advanced users. For such users we can provide ability to add custom (or user defined) function using Java programming language. 

The initial version will support simple scalar function which accepts an input <T> and returns an output<T>. Where T represent the data type. The UDF author should make sure data type T matches with underlying column data type.

**Comment by arrah** [comment]
Should we use ... operator so that it can take variable number of input
with <T> which depending upon function we can type cast like for camelCase
T.tostring()

**Comment by arun-y** [comment]
Yes, we can use vargs as well. Will include the same.
